### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 0Mayank** [0Mayank/basic-calculator#1]
- [x] Use aspect-ratio property on the buttons instead of hard-coded widths.
- [x] Center it on computers
- [x] Responsive layout for phones
